FROM node:22-slim

# Установка OpenSSL (для исправления проблем с Prisma https://github.com/prisma/prisma/discussions/22519)
RUN apt-get update && apt-get install -y openssl

# Установка Bun
RUN apt-get install -y curl unzip
RUN curl -fsSL https://bun.sh/install | bash
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

# Установка рабочей директории
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./ 

# Копируем папку prisma
COPY prisma ./prisma/

RUN rm -rf node_modules
# RUN npm install
# Устанавливаем зависимости через Bun
RUN bun install --frozen-lockfile

# Копируем все файлы проекта в контейнер
COPY . .

# Генерация Prisma Client для нужной платформы
RUN npx prisma generate

# Выполняем сборку
# RUN npm run build

# Открываем порты
EXPOSE 1337

# Команда для запуска через bun
CMD ["npm", "run", "start"]
